import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomeLayout from "@/components/layouts/homeLayout/HomeLayout";
import { CartProvider } from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <HomeLayout>{children}</HomeLayout>
        </CartProvider>
      </body>
    </html>
  );
}
